user  nginx; #identify the user that Nginx will run as
worker_processes  auto; #number of worker processes, auto will set it to the number of CPU cores

error_log  /var/log/nginx/error.log notice; #log level can be debug, info, notice, warn, error, crit, alert, emerg
pid        /run/nginx.pid; #pid file location, crucial for managing and controlling the Nginx server process.


events {
    worker_connections  1024; #maximum number of simultaneous (concurrent) connections that can be opened by a worker process [Higher memory consumption, Potenctially higher CPU utilization, and increaded demand for file descriptors]
}


http { #Includes directives for configuring the HTTP server, which is the most common use case for Nginx.
    ###RATE LIMITING###
    # Define a limit zone named 'mylimit' that tracks IP addresses, storing 10MB of state
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s; #limit the rate of requests from a single IP address to 10 requests per second
    ###END RATE LIMITING###

    server {
        listen       80; #port to listen on
        listen  [::]:80; #IPv6 support
        server_name  localhost; #server name, can be a domain or IP address

        ####ACCESS CONTROL#####
        #access_log  /var/log/nginx/host.access.log  main;
        location /admin {
            allow 192.168.1.0/24; #allow access from this IP range
            allow 203.0.113.45; #allow access from this specific IP
            deny all; #deny access from all other IPs\
        }

        location / {
            allow all; #allow access from all IPs
        }

        location /protected {
            auth_basic "Restricted Content"; #prompt for authentication
            auth_basic_user_file /etc/nginx/.htpasswd; #path to the password file
        }
        ####END ACCESS CONTROL#####

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

    ####SSL CONFIGURATION####
    #server {
    #    listen 443 ssl http2; #listen on port 443 for SSL
    #    server_name example.com; #server name
    #
    #    ssl_certificate /etc/ssl/certs/example.com.crt; #path to the SSL certificate
    #    ssl_certificate_key /etc/ssl/private/example.com.key; #path to the SSL certificate key
    #
    #    ssl_protocols TLSv1.2 TLSv1.3; #supported SSL protocols
    #    ssl_ciphers 'HIGH:!aNULL:!MD5'; #supported SSL ciphers
    #    ssl_prefer_server_ciphers on; #prefer server ciphers
    #
    #    ssl_session_cache shared:SSL:10m; #cache for SSL sessions
    #    ssl_session_timeout 10m; #timeout for SSL sessions
    #
    
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
